### PR TITLE
[release-2.6] Replace golang.org/x/text version

### PR DESCRIPTION
**Pull request by JustinKuli**
Refs:
 - https://github.com/stolostron/backlog/issues/26341

Signed-off-by: Justin Kulikauskas <jkulikau@redhat.com>

### CODE REVIEW

**Review by dhaiducek — APPROVED** [review]

**Comment by dhaiducek** [comment]
Also, the referenced issue is for `2.7`. Was there a `2.6` issue?

**Comment by JustinKuli** [comment]
There was no 2.6 issue, but in Slack it was mentioned that we should cherry-pick these kinds of fixes to the most recently released version.

**Comment by dhaiducek** [comment]
> There was no 2.6 issue, but in Slack it was mentioned that we should cherry-pick these kinds of fixes to the most recently released version.

Yeah, my bad. I actually deleted my comment because I remembered that an issue is only created for the latest version now.

**Review by willkutler — APPROVED** [review]

**Comment by dhaiducek** [comment]
@JustinKuli Is this ready to go? Looks like it had a hold on it so it didn't merge. Might need a rebase now to pick up my workflow updates.

**Comment by JustinKuli** [comment]
@dhaiducek yeah, not sure how I lost track of this one.

/unhold

**Review by dhaiducek — APPROVED** [review]

**Pull request merged**
